version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
    create_infrastructure:  # Choose any name, such as `build`
        # The primary container, where your job's commands will run
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout 
          - run:
              name: 
              command: |
                apk add --update ansible
    configure_infrastructure:  # Choose any name, such as `build`
        # The primary container, where your job's commands will run
        docker:
          - image: python:3.7-alpine3.11
        steps:
          - checkout
          - add_ssh_keys:
              Fingerprint: ["c1:e7:aa:f3:f7:c1:f3:28:83:9f:70:75:8c:a6:df:6f"]
          - run:
              name: Install dependencies
              command: |
                apk add --update ansible
          - run:
              name: Configure server
              command: |
                ansible-playbook -i inventory main.yml
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        - configure_infrastructure
        